### ISSUE TITLE
Compact Rinex

### ISSUE THREAD

**Issue by Juerg-Liechti** [sharov-am/Rinex-3.0-Parser#4]

**Comment by Juerg-Liechti** [comment]
I tested compact Rinex today.
The header worked fine but i got a few problems on the next records.
> 2018  8 30  8 28 37.0000000  0 31      **G10R15R24R14G31G26G16G27R17J 1R 7R 8G20G29G 5R13R23G21C 9C13C11C16C 5C14E 5E27E26E 3E 1S36S20**

**Comment by sharov-am** [comment]
Hi. 

Can you provider full file header and some few epochs?

**Comment by Juerg-Liechti** [comment]
3.0                 COMPACT RINEX FORMAT                    CRINEX VERS   / TYPE
NetR9 5.22                              30-AUG-18 08:28:37  CRINEX PROG / DATE
     3.03           OBSERVATION DATA    M (MIXED)           RINEX VERSION / TYPE
NetR9 5.22          Receiver Operator   20180830 082837 UTC PGM / RUN BY / DATE
ZIM3                                                        MARKER NAME
14001M008                                                   MARKER NUMBER
GEODETIC                                                    MARKER TYPE         
Trimble NetR9       SWISSTOPO                               OBSERVER / AGENCY   
5229K50741          TRIMBLE NETR9       5.22                REC # / TYPE / VERS
60369               TRM59800.00     NONE                    ANT # / TYPE
  4331300.1600   567537.0830  4633133.5100                  APPROX POSITION XYZ
        0.0000        0.0000        0.0000                  ANTENNA: DELTA H/E/N
G   12 C1C L1C S1C C2W L2W S2W C2X L2X S2X C5X L5X S5X      SYS / # / OBS TYPES
S    6 C1C L1C S1C C5I L5I S5I                              SYS / # / OBS TYPES
R   12 C1C L1C S1C C1P L1P S1P C2C L2C S2C C2P L2P S2P      SYS / # / OBS TYPES
E   12 C1X L1X S1X C5X L5X S5X C7X L7X S7X C8X L8X S8X      SYS / # / OBS TYPES
J   18 C1C L1C S1C C1X L1X S1X C1Z L1Z S1Z C2X L2X S2X C5X  SYS / # / OBS TYPES
       L5X S5X C6X L6X S6X                                  SYS / # / OBS TYPES
C    9 C2I L2I S2I C7I L7I S7I C6I L6I S6I                  SYS / # / OBS TYPES
     1.000                                                  INTERVAL
  2018     8    30     8    28   37.0000000     GPS         TIME OF FIRST OBS
G L2X -0.25000                                              SYS / PHASE SHIFT   
R L1P  0.25000                                              SYS / PHASE SHIFT   
R L2C -0.25000                                              SYS / PHASE SHIFT   
J L2X -0.25000                                              SYS / PHASE SHIFT   
DBHZ                                                        SIGNAL STRENGTH UNIT
  9 R01  1 R07  5 R08  6 R13 -2 R14 -7 R15  0 R17  4 R23  3 GLONASS SLOT / FRQ #
    R24  2                                                  GLONASS SLOT / FRQ #
                                                            GLONASS COD/PHS/BIS 
                                                            END OF HEADER       
> 2018  8 30  8 28 37.0000000  0 31      G10R15R24R14G31G26G16G27R17J 1R 7R 8G20G29G 5R13R23G21C 9C13C11C16C 5C14E 5E27E26E 3E 1S36S20
3&-336401000
3&24916954383 3&130939505633 3&37200 3&24916961758 3&102030787612 3&21300 3&24916961379 3&102030782618 3&37100 3&24916960340 3&97779500794 3&43600 0616&&0313&&0616&&0717&&
3&21830803586 3&116657196494 3&43800 3&21830803238 3&116657198496 3&42000 3&21830809129 3&90733414813 3&37500 3&21830808652 3&90733387792 3&36300 0717&&0717&&0616&&0616&&
3&19890590945 3&106363913617 3&46900 3&19890590945 3&106363932619 3&45100 3&19890593121 3&82727528479 3&37600 3&19890593074 3&82727629516 3&37200 0717&&0717&&0616&&0616&&
3&19708134141 3&105055440253 3&52800 3&19708133035 3&105055444245 3&52100 3&19708138078 3&81709805519 3&49600 3&19708137344 3&81709800513 3&49600 0818&&0818&&0818&&0818&&
3&24105840930 3&126677074846 3&42100 3&24105846512 3&98709379218 3&26000 3&24105846164 3&98709389200 3&38900    0717&&0414&&0616&&&&&&&&
3&20239325898 3&106358386931 3&52800 3&20239333957 3&82876687683 3&48800 3&20239333039 3&82876689678 3&52800 3&20239331668 3&79423480093 3&57200 0818&&0818&&0818&&0919&&
3&20749122219 3&109037407770 3&49100 3&20749126016 3&84964214487 3&41900       0818&&0616&&&&&&&&&&&&&&
3&22731157133 3&119453113621 3&41400 3&22731163238 3&93080320275 3&31100 3&22731162844 3&93080325273 3&44300 3&22731162984 3&89201974654 3&49800 0616&&0515&&0717&&0818&&
3&23312525406 3&124750041672 3&43000 3&23312524703 3&124750040684 3&40800 3&23312529699 3&97027807678 3&40500 3&23312530621 3&97027826671 3&39500 0717&&0616&&0616&&0616&&
3&44503874797 3&233869434113 3&31600 3&44503875457 3&233869407123 3&35400 3&44503873820 3&233869226993 3&31200 3&44503879063 3&182235963755 3&33500 3&44503880172 3&174642784809 3&34800 3&44503871969 3&189829054554 3&34900 0515&&0515&&0515&&0515&&0515&&0515&&
3&22692841563 3&121476581028 3&42200 3&22692841129 3&121476574069 3&40800 3&22692845129 3&94481803957 3&41300 3&22692845082 3&94481808931 3&41500 0717&&0616&&0616&&0616&&
3&22886616578 3&122556823520 3&44400 3&22886616301 3&122556806521 3&42900 3&22886619590 3&95321988443 3&41300 3&22886620172 3&95321979441 3&40500 0717&&0717&&0616&&0616&&
3&22859019445 3&120124948848 3&43900 3&22859024281 3&93603889350 3&28900       0717&&0414&&&&&&&&&&&&&&
3&22918605523 3&120438125428 3&47500 3&22918610223 3&93847867363 3&32600 3&22918610527 3&93847871367 3&42100    0717&&0515&&0717&&&&&&&&
3&24991217078 3&131329741103 3&38900 3&24991223504 3&102334886976 3&19600 3&24991223582 3&102334889969 3&36700    0616&&0313&&0616&&&&&&&&
3&20716641742 3&110625701501 3&43400 3&20716638918 3&110625705510 3&42000 3&20716644465 3&86042206559 3&39800 3&20716643063 3&86042211572 3&39700 0717&&0717&&0616&&0616&&
3&19703912648 3&105402657941 3&52800 3&19703911449 3&105402633947 3&51500 3&19703916461 3&81979884934 3&45000 3&19703917840 3&81979820940 3&43500 0818&&0818&&0717&&0717&&
3&20845043414 3&109541460784 3&51100 3&20845047035 3&85357002974 3&45100       0818&&0717&&&&&&&&&&&&&&
3&41643607023 3&216849193063 3&32400 3&41643605668 3&167681526487 3&33800    0515&&0515&&&&&&&&
3&40635399328 3&211599172839 3&37300 3&40635400508 3&163621880946 3&36900 3&40635389488 3&171941647604 3&32300 0616&&0616&&0515&&
3&23913863578 3&124525760201 3&47400 3&23913859953 3&96291197730 3&47600 3&23913850582 3&101187345092 3&47500 0717&&0717&&0717&&
3&40841524727 3&212672548044 3&36700 3&40841525672 3&164451896499 3&33700    0616&&0515&&&&&&&&
3&39652572203 3&206481317040 3&36200 3&39652567762 3&159664451917 3&39600 3&39652561059 3&167782968986 3&37200 0616&&0616&&0616&&
3&25036713953 3&130372758862 3&40900 3&25036711184 3&100812466452 3&44000 3&25036700750 3&105938508729 3&42500 0616&&0717&&0717&&
3&28060822461 3&147460620581 3&38600 3&28060827957 3&110116719422 3&41300 3&28060826133 3&112989317510 3&39500 3&28060827898 3&111553018571 3&44200 0616&&0616&&0616&&0717&&
3&24724077984 3&129925899248 3&50700 3&24724081891 3&97022597982 3&51200 3&24724080605 3&99553614625 3&51200 3&24724081660 3&98288109404 3&53600 0818&&0818&&0818&&0818&&
3&25314527648 3&133028747864 3&41100 3&25314530277 3&99339675351 3&40600 3&25314532504 3&101931135041 3&43900 3&25314533539 3&100635407291 3&46000 0616&&0616&&0717&&0717&&
3&28076304469 3&147541979468 3&38800 3&28076310375 3&110177476831 3&41800 3&28076309273 3&113051666839 3&41800 3&28076309984 3&111614573437 3&45400 0616&&0616&&0616&&0717&&
3&26828282289 3&140983576212 3&43700 3&26828286035 3&105279960468 3&44900 3&26828285043 3&108026386176 3&45300 3&26828285242 3&106653175431 3&48800 0717&&0717&&0717&&0818&&
3&37981727344 3&199595213859 3&44600 3&37981713313 3&149048476797 3&46400 0717&&0717&&
3&38277674906 3&201150564054 3&39100    0616&&&&&&&&
                    8
0

**Comment by Juerg-Liechti** [comment]
[ZIM300CHE_R_20182420828_01H_01S_MO.zip](https://github.com/sharov-am/Rinex-3.0-Parser/files/2483218/ZIM300CHE_R_20182420828_01H_01S_MO.zip)

**Comment by Juerg-Liechti** [comment]
Added a complete Compact Rinex File.

**Comment by sharov-am** [comment]
Hi!

I fix issue with ZIM300CHE_R_20182420828_01H_01S_MO.rnx. If everything is fine you can close this issue.

**Comment by Juerg-Liechti** [comment]
I have still some problems in the first line after the header...
The Message is -> Sequence contains no elements

**Comment by sharov-am** [comment]
Hi.

The file you attached is in Hatanaka(crx) format, you should convert it to rinex via crx2rnx util or simliar. I don't parse Hatanka format for now.

**Comment by Juerg-Liechti** [comment]
Ok, you just read the header. No Problem. The header is fine!
